# Generated by Django 3.2.4 on 2021-09-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40, null=True)),
                ('course_code', models.CharField(max_length=20, null=True)),
                ('trainer', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('class_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(null=True)),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
            ],
        ),
    ]
