# Generated by Django 3.2.4 on 2021-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('national_id', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='trainer_images/')),
                ('resume', models.FileField(null=True, upload_to='trainer_documents/')),
                ('salary', models.PositiveBigIntegerField(null=True)),
                ('course_name', models.CharField(max_length=20, null=True)),
                ('company_name', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('3', 'Other')], default='other', max_length=11, null=True)),
            ],
        ),
    ]
