# Generated by Django 3.2.4 on 2021-09-27 12:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('national_id', models.CharField(max_length=30, null=True)),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('image', models.ImageField(null=True, upload_to='trainer_images/')),
                ('resume', models.FileField(null=True, upload_to='trainer_documents/')),
                ('salary', models.PositiveBigIntegerField(null=True)),
                ('course_name', models.CharField(max_length=40, null=True)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='other', max_length=11, null=True)),
            ],
        ),
    ]
