# Generated by Django 3.2.4 on 2021-08-10 12:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, null=True, region=None),
        ),
    ]
