# Generated by Django 3.2.4 on 2021-08-10 14:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='national_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
