# Generated by Django 3.2.4 on 2021-08-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('venue', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
