# Generated by Django 3.2.4 on 2021-09-27 12:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.PositiveSmallIntegerField(default=20, null=True)),
                ('nationality', models.CharField(choices=[('0', 'Kenyan'), ('1', 'Ugandan'), ('3', 'Rwandan'), ('4', 'South Sudanese')], default='Kenyan', max_length=11)),
                ('national_id', models.CharField(default=' ', max_length=30)),
                ('email', models.EmailField(default='shadyaobuya@gmail.com', max_length=25)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=' ', max_length=30, region=None)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('admission_date', models.DateField(null=True)),
                ('academic_year', models.PositiveBigIntegerField(default=2021)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Female', max_length=11)),
                ('laptop_number', models.CharField(max_length=10, null=True)),
                ('class_name', models.CharField(default='Lovelace', max_length=20)),
                ('guardian_name', models.CharField(default=' ', max_length=20)),
                ('guardian_number', phonenumber_field.modelfields.PhoneNumberField(default='+254729113940', max_length=30, region=None)),
            ],
        ),
    ]
