# Generated by Django 3.2.4 on 2021-09-04 11:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('nationality', models.CharField(choices=[('0', 'Kenyan'), ('1', 'Ugandan'), ('3', 'Rwandan'), ('4', 'South Sudanese')], default='Kenyan', max_length=11)),
                ('national_id', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('admission_date', models.DateField(null=True)),
                ('academic_year', models.PositiveBigIntegerField(null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=11, null=True)),
                ('laptop_number', models.CharField(max_length=10, null=True)),
                ('class_name', models.CharField(max_length=20, null=True)),
                ('guardian_name', models.CharField(max_length=20, null=True)),
                ('guardian_number', phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None)),
            ],
        ),
    ]
