# Generated by Django 3.2.4 on 2021-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210727_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_number',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('3', 'Other')], default='other', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('0', 'Kenyan'), ('1', 'Ugandan'), ('3', 'Rwandan'), ('4', 'South Sudanese')], max_length=11, null=True),
        ),
    ]
