# Generated by Django 3.2.4 on 2021-07-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210730_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('0', 'Kenyan'), ('1', 'Ugandan'), ('3', 'Rwandan'), ('4', 'South Sudanese')], default='Kenyan', max_length=11, null=True),
        ),
    ]
