# Generated by Django 3.2.4 on 2021-08-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210801_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
