# Generated by Django 3.2.4 on 2021-08-10 14:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_medical_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, null=True, region=None),
        ),
    ]
